import React, { useState, useEffect } from "react";
import { FaBars, FaPlus, FaMinus, FaDownload } from "react-icons/fa";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

const Annexure = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [claimFormData, setClaimFormData] = useState({});

  useEffect(() => {
    fetch("/personalInfo.json")
      .then((res) => res.json())
      .then((data) => {
        setClaimFormData(data.claimFormData || {});
      })
      .catch((err) => console.error("Error loading data:", err));
  }, []);

  const toggleOpen = () => {
    setIsOpen((prev) => !prev);
  };

  const handleDownload = () => {
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.setTextColor("#2c3e50");
    doc.text("EPFO Claim Form Annexure", 20, 20);

    doc.setDrawColor("#2980b9");
    doc.setLineWidth(0.5);
    doc.line(20, 22, 190, 22);

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor("#333");
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 30);

    const form = claimFormData;

    const formRows = [
      ["Employee Name", form.employeeName || "-"],
      ["Father/Husband Name", form.fatherHusbandName || "-"],
      ["Date of Birth", form.dob || "-"],
      ["Mobile Number", form.mobile || "-"],
      ["Aadhaar Number", form.aadhaar || "-"],
      ["PAN", form.pan || "-"],
      ["Bank Account", form.bankAccount || "-"],
      ["IFSC Code", form.ifsCode || "-"],
      ["Branch Name & Address", form.branchNameAddress || "-"],
      ["Member ID", form.memberId || "-"],
      ["Date of Joining EPF", form.dojEpf || "-"],
      ["Date of Joining EPS", form.dojEps || "-"],
      ["Date of Exit EPF", form.doeEpf || "-"],
      ["Date of Exit EPS", form.doeEps || "-"],
      ["Reason of Leaving", form.reasonOfLeaving || "-"],
    ];

    autoTable(doc, {
      startY: 40,
      theme: "grid",
      head: [["Claim Form Details", ""]],
      body: formRows,
      headStyles: { fillColor: "#2980b9", textColor: "#fff" },
      styles: { fontSize: 11 },
      columnStyles: {
        0: { fontStyle: "bold", cellWidth: 70 },
        1: { cellWidth: 110 },
      },
    });

    doc.setFontSize(10);
    doc.setTextColor("#999");
    doc.text("Generated by Annexure Tool", 20, 285);

    doc.save("Claim_Form_Annexure.pdf");
  };

  return (
  <div className="p-3 shadow-md mt-12 w-full">
      <div className="border border-gray-400 rounded-md shadow-lg">
        <div className="flex items-center justify-between bg-blue-100 px-4 py-2 rounded-t-md">
          <div className="flex items-center space-x-2 text-blue-900">
            <FaBars />
            <span className="font-semibold">Download Annexure K</span>
          </div>
          <button onClick={toggleOpen} className="text-blue-800 text-xl">
            {isOpen ? <FaMinus /> : <FaPlus />}
          </button>
        </div>

        {isOpen && (
          <div className="bg-gray-50 p-4 border-t border-gray-300">
            <button
              onClick={handleDownload}
              className="bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700 flex items-center space-x-2"
            >
              <FaDownload />
              <span>Download PDF</span>
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default Annexure;
